// Tests for scripts/check-batch-001.mjs against a local node:http server that stands
// in for the deployed site: it serves the record on /batch/001 and 301s /batch/1 and
// /batch/01, matching firebase.json's hosting redirects. No network, no firebase.

import { test } from "node:test";
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { createServer } from "node:http";
import { existsSync, readFileSync, renameSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolve, dirname } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..", "..");
const CHECK_SCRIPT = resolve(ROOT, "scripts", "check-batch-001.mjs");
// M3.4: /batch/001 is generated by the site/app/batch/[nnn] route (D48), so
// the record these tests diff against is the build output. Run
// "npm run build --workspace site" before running this file directly; the
// root "npm test" already builds first. next.config.mjs's `output:
// "export"` with `trailingSlash: false` writes a flat batch/001.html file,
// not batch/001/index.html.
const RECORD_PATH = resolve(ROOT, "site", "out", "batch", "001.html");
if (!existsSync(RECORD_PATH)) {
  throw new Error(
    `${RECORD_PATH} not found. Run "npm run build --workspace site" before running scripts/test/check-batch-001.test.mjs.`,
  );
}
const RECORD = readFileSync(RECORD_PATH);

function startServer(body) {
  const server = createServer((req, res) => {
    if (req.url === "/batch/001") {
      res.writeHead(200, { "Content-Type": "text/html" });
      res.end(body);
      return;
    }
    if (req.url === "/batch/1" || req.url === "/batch/01") {
      res.writeHead(301, { Location: "/batch/001" });
      res.end();
      return;
    }
    res.writeHead(404);
    res.end();
  });
  return new Promise((resolve) => {
    server.listen(0, "127.0.0.1", () => resolve(server));
  });
}

// spawnSync would block this process's event loop while the child runs — but the
// child needs to talk to the http server we run in *this* process, so a synchronous
// spawn deadlocks (the server can't service the request until spawnSync returns, and
// spawnSync won't return until the child gets its response). Use async spawn instead.
function runCheck(baseUrl) {
  return new Promise((resolvePromise, reject) => {
    const child = spawn(process.execPath, [CHECK_SCRIPT, "--url", baseUrl], { cwd: ROOT });
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (c) => (stdout += c.toString()));
    child.stderr.on("data", (c) => (stderr += c.toString()));
    child.on("close", (status) => resolvePromise({ status, stdout, stderr }));
    child.on("error", reject);
  });
}

test("passes against a server that serves the exact record and correct redirects", async () => {
  const server = await startServer(RECORD);
  const { port } = server.address();
  try {
    const { status, stdout } = await runCheck(`http://127.0.0.1:${port}`);
    assert.equal(status, 0);
    assert.match(stdout, /PASS.*\/batch\/001/);
    assert.match(stdout, /PASS.*\/batch\/1\b/);
    assert.match(stdout, /PASS.*\/batch\/01\b/);
    assert.match(stdout, /all good\./);
  } finally {
    server.close();
  }
});

test("exits 2 when the served body differs from the record and shows which lines differ", async () => {
  // Tamper: add extra content at the end (live site ahead by byte count)
  const tampered = Buffer.concat([RECORD, Buffer.from("<!-- tampered -->")]);
  const server = await startServer(tampered);
  const { port } = server.address();
  try {
    const { status, stdout } = await runCheck(`http://127.0.0.1:${port}`);
    assert.equal(status, 2);
    assert.match(stdout, /FAIL.*\/batch\/001/);
    assert.match(stdout, /body differs/);
    assert.match(stdout, /Differing content:/);
    assert.match(stdout, /Live site:/);
    assert.match(stdout, /The live site has unexpected content/);
  } finally {
    server.close();
  }
});

test("exits 1 for D28 difference (ingredient line without percentages in repo, with percentages on live)", async () => {
  // Create two versions: repo has no percentages (D28 correct), live has them (old)
  const recordStr = RECORD.toString("utf8");
  const oldIngredientLine =
    '<p>Prawns (59%), dates (22%), vinegar, gingelly (sesame) oil, garlic, green chilli, ginger, salt, Kashmiri chilli powder, red chilli powder, sugar, compounded asafoetida (gum arabic, wheat flour, asafoetida), mustard, curry leaves, fenugreek, turmeric.</p>';
  const newIngredientLine =
    "<p>Prawns, dates, vinegar, gingelly (sesame) oil, garlic, green chilli, ginger, salt, Kashmiri chilli powder, red chilli powder, sugar, compounded asafoetida (gum arabic, wheat flour, asafoetida), mustard, curry leaves, fenugreek, turmeric.</p>";

  // Repo has the new line (no percentages, per D28), create a live version with the old line
  const liveVersionStr = recordStr.replace(newIngredientLine, oldIngredientLine);
  const liveVersion = Buffer.from(liveVersionStr, "utf8");

  const server = await startServer(liveVersion);
  const { port } = server.address();
  try {
    const { status, stdout } = await runCheck(`http://127.0.0.1:${port}`);
    assert.equal(status, 1, "D28 difference should exit with code 1");
    assert.match(stdout, /FAIL.*\/batch\/001/);
    assert.match(stdout, /Differing content:/);
    assert.match(stdout, /Repo record:.*Prawns, dates, vinegar/);
    assert.match(stdout, /Live site:.*Prawns \(59%\), dates \(22%\)/);
    // D28 case: script detects the ingredient line difference and says repo is ahead
    assert.match(stdout, /The repo is ahead.*D28 implementation/);
    assert.match(
      stdout,
      /A deploy of the customer site is owed to bring it up to date/
    );
  } finally {
    server.close();
  }
});
test("exits 2 when a redirect is missing (404 instead of 301)", async () => {
  const server = createServer((req, res) => {
    if (req.url === "/batch/001") {
      res.writeHead(200, { "Content-Type": "text/html" });
      res.end(RECORD);
      return;
    }
    res.writeHead(404);
    res.end();
  });
  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  const { port } = server.address();
  try {
    const { status, stdout } = await runCheck(`http://127.0.0.1:${port}`);
    assert.equal(status, 2);
    assert.match(stdout, /PASS.*\/batch\/001/);
    assert.match(stdout, /FAIL.*\/batch\/1\b/);
    assert.match(stdout, /expected 301, got 404/);
  } finally {
    server.close();
  }
});

test("--project staging targets the staging project's URL from .firebaserc, not a hard-coded name", async () => {
  const firebaserc = JSON.parse(readFileSync(resolve(ROOT, ".firebaserc"), "utf8"));
  const expectedBase = `https://${firebaserc.projects.staging}.web.app`;

  // Don't wait for the real network call to finish (there is no server listening
  // at that address in this test) — just capture the "checking ..." line the
  // script prints before it dials out, then kill it.
  const child = spawn(process.execPath, [CHECK_SCRIPT, "--project", "staging"], { cwd: ROOT });
  let stdout = "";
  await new Promise((resolvePromise) => {
    child.stdout.on("data", (c) => {
      stdout += c.toString();
      if (stdout.includes("checking ")) resolvePromise();
    });
  });
  child.kill();
  assert.match(stdout, new RegExp(`checking ${expectedBase.replace(/[.]/g, "\\.")} `));
});

test("fails with a clear message when the build output is missing", async () => {
  // Moves the real build output aside for the duration of this one test, so
  // the script has to hit its "run npm run build first" guard, then puts it
  // back: this test must never leave the repo without the file other tests
  // in this suite depend on.
  const movedAside = `${RECORD_PATH}.movedForTest`;
  renameSync(RECORD_PATH, movedAside);
  try {
    const server = await startServer(RECORD); // unreachable if the guard fires first
    const { port } = server.address();
    try {
      const { status, stderr } = await runCheck(`http://127.0.0.1:${port}`);
      assert.equal(status, 2);
      assert.match(stderr, /Build output not found/);
      assert.match(stderr, /npm run build/);
    } finally {
      server.close();
    }
  } finally {
    renameSync(movedAside, RECORD_PATH);
  }
});
